//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public Musteri()
        {
            this.Rezervasyon = new HashSet<Rezervasyon>();
        }
    
        public int musteriID { get; set; }
        public string musteriAdi { get; set; }
        public string musteriSoyadi { get; set; }
        public Nullable<System.DateTime> dogumTarihi { get; set; }
        public Nullable<int> cinsiyet { get; set; }
        public string telefon { get; set; }
        public string ePosta { get; set; }
        public string aciklama { get; set; }
    
        public virtual ICollection<Rezervasyon> Rezervasyon { get; set; }
    }
}
