//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oda
    {
        public Oda()
        {
            this.Rezervasyon = new HashSet<Rezervasyon>();
        }
    
        public int odaNo { get; set; }
        public Nullable<int> odaTur { get; set; }
    
        public virtual OdaTur OdaTur1 { get; set; }
        public virtual ICollection<Rezervasyon> Rezervasyon { get; set; }
    }
}
