//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdaTur
    {
        public OdaTur()
        {
            this.Bilgilendirme = new HashSet<Bilgilendirme>();
            this.Oda = new HashSet<Oda>();
        }
    
        public int turID { get; set; }
        public string turAdi { get; set; }
        public Nullable<int> turAdet { get; set; }
    
        public virtual ICollection<Bilgilendirme> Bilgilendirme { get; set; }
        public virtual ICollection<Oda> Oda { get; set; }
    }
}
