//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyon
    {
        public int rezervID { get; set; }
        public Nullable<int> musteriID { get; set; }
        public Nullable<int> odaNo { get; set; }
        public Nullable<System.DateTime> rezervTarih { get; set; }
        public Nullable<int> gunSayi { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Oda Oda { get; set; }
    }
}
